name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  uuid: ^3.0.7
