name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  json_annotation: ^4.1.0
  equatable: ^2.0.5
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.2
  mocktail: ^1.0.0
  test: ^1.16.4
  coverage: ^1.0.3
