final List<String> teamNameMock = [
  'Arsenal',
  'Liverpool',
  'Hotspur',
  'Saints FC',
  'Chelsea',
  'Everton',
  'Newcastle',
  'WestHam Utd',
  'B.Dortmund',
  'Forest',
  'Rovers',
  'Villa',
  'Man City',
  'Norwich',
  'Wolves',
  'Leicester ',
  'Watford',
  'Middlesbrough',
  'Rangers',
  'Juventus',
  'Sheffield Utd',
  'Bournemouth',
  'Brentford',
  'Birmingham',
  'Cardiff',
  'Charlton',
  'Fulham',
  'Leeds United',
  'Brewers',
  'Browns',
  'Milan',
  'Burnley',
  'Preston',
  'Brighton',
  'Ipswich',
  'Coventry',
  'Reading',
  'Buccaneers',
  'Bulls',
  'Lions',
  'Leverkusen',
  'Sheffield',
  'Boca Juniors',
  'Sunderland',
  'Barnet',
  'Wigan Athletic',
  'Millwall',
];
