final List<String> teamNameMock = [
  'Arsenal',
  'Liverpool',
  'Hotspur',
  'Saints FC',
  'Chelsea',
  'Everton',
  'Newcastle United',
  'West Ham United',
  'Borussia Dortmund',
  'Forest',
  'Rovers',
  'Villa',
  'Manchester City',
  'West Bromwich Albion',
  'Norwich City',
  'Wolverhampton Wanderers',
  'Leicester City',
  'Watford',
  'Middlesbrough',
  'Rangers',
  'Juventus',
  'Sheffield United',
  'A.F.C. Bournemouth',
  'Brentford',
  'Birmingham City',
  'Cardiff City',
  'Charlton Athletic',
  'Fulham',
  'Leeds United',
  'Queens Park Rangers',
  'Brewers',
  'Browns',
  'Milan',
  'Burnley',
  'Preston North End',
  'Brighton & Hove Albion',
  'Ipswich Town',
  'Huddersfield Town',
  'Coventry City',
  'Reading',
  'Buccaneers',
  'Bulls',
  'Lions',
  'Bayer 04 Leverkusen',
  'Sheffield Wednesday',
  'Boca Juniors',
  'Borussia Mönchengladbach',
  'Sunderland',
  'Barnet',
  'Wigan Athletic',
  'Millwall',
];
